project_id = "dbbntsmjshndkvyrvsad"

[functions.whatsapp-connect]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send-message]
verify_jwt = true

[functions.execute-whatsapp-flow]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.facebook-reply]
verify_jwt = false

[functions.facebook-connect]
verify_jwt = true

[functions.facebook-auth]
verify_jwt = false

[functions.instagram-connect]
verify_jwt = true

[functions.instagram-webhook]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = true

[functions.scan-subscribers]
verify_jwt = true

[functions.broadcast-message]
verify_jwt = true

[functions.send-message]
verify_jwt = true

[functions.webhook-test]
verify_jwt = true

[functions.execute-flow]
verify_jwt = true

[functions.verify-domain]
verify_jwt = true

[functions.bkash-payment]
verify_jwt = false

[functions.bkash-subscription-payment]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.piprapay-create-charge]
verify_jwt = true

[functions.piprapay-webhook]
verify_jwt = false

[functions.piprapay-verify-payment]
verify_jwt = true

[functions.website-widget-loader]
verify_jwt = false

[functions.website-widget-config]
verify_jwt = false

[functions.website-widget-message]
verify_jwt = false

[functions.website-send-message]
verify_jwt = true

[functions.website-fetch-messages]
verify_jwt = false

[functions.co-browse-session]
verify_jwt = true

[functions.video-call-session]
verify_jwt = true

[functions.send-address-confirmation]
verify_jwt = false

[functions.send-templated-email]
verify_jwt = false

[functions.check-page-activation]
verify_jwt = true
